dist: trusty
sudo: required
language: node_js
node_js:
  - 9.5.0

addons:
  chrome: stable

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_deploy: "./compile-build.sh release.tar.gz dist"

deploy:
  file: release.tar.gz
  provider: releases
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: ahBG2wwDa4WxZDpzDDTpkokpNhmtUU3H2vhTKWfgpY0L7urmZUKDrZeqo6FBnUA+yj5zm9KKjcYyrnGFbScHKaXvxrID1Q4c/Pc7JIImTfcIY4/AXuoQpXE3YAHj2jTjGoEr5Yv1P+otZyUVWW/utG6C4CzB5xxpwiSWGjeuGc/pQ2qqUilr5TOoao0JCaMUasBfmJErSVC9r+N/Qu02FFGa7b+2XZCWbscWqfMUx3Dvs4XFDOtTYrdwiVXL2w/72+BBbXniMQxcrAKJccEJYgdebxPb6eYvhUD1WpGsqioLnpQPICjgFwQXGUQjVxYKpZjNTN4yGzHt2d+BW5SBj6KoF/1FVbZTxB29cphEuYY57uw6JzDAGQiWKqmz+NgbjVjPYHyDsvMZjpau0a+FLJ930G3CnVf2kD3AN0nK/cOo/cqscE9e+tuC7LLH9GBplbbSAkbcZbzYjekGOh0gfcQQR9RKfbj56gHXSFaa4+sxTcRUw6oKW2Y4sKsQyq7lPp1YTSECiY7mEN0YaI+D0+EtZwny+mRb+6pFlW0bISDfaunBTS/TGNZLBxqosf8WCUtmuqnNJ0zx16euv2PsNOrItk7aJrjK+cSdzVPmyYUuPYfwbf7pj2N5e+QnEySmjhAKQrjhHmQRgny9hzYuhkH2RlWP6LPq9S0tnooeTIw=
