dist: xenial
sudo: required
language: node_js
node_js:
- 11.14.0
addons:
  chrome: stable
before_script:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - yarn test
  - yarn lint
before_deploy:
  - ./compile-build.sh release.tar.gz dist
  - export TAG_NAME=${TRAVIS_BRANCH}/$(date +'%Y-%m-%d/%H%M%S')
  - git tag "${TAG_NAME}"

deploy:
  provider: releases
  name: ${TAG_NAME}
  skip_cleanup: true
  file: release.tar.gz
  api_key:
    secure: Bu5KtZf7NJoebOsYbX0HlpRgna9XGhC6wdvYEaMkPMlpXhZMsqClW8ztX1UtlUBKHfQVKB4PGjfEFqPc3UA7wCNswkQg+vP78zdEUtfllcpJeB3vWxbRIhBBmzxdjb8+uzbzLJNSCfhVp8Drll6yY4iRtWK03iYGUYIzuleVRXPVy2rbnmrtE+CexxzOAS4r1BcwY7iAJuYXbWLqlyNmRZKHyKY0vjC+dWrgDwQ+rM2iQaaJIxETrrNdDG75WROk9LRTVf30wN1v10MLmFnQqe5dElCtCLXXFsBnay2ojpwfEQUvGFKVnVl1PaSINgpuNHi6khaYNSacGj7C4nKHtyRiypJzfw6mumBUpPXnidAF5+FPV2gZTUW10bH66WfPz6rWzjBogA17GnA8OjxDBUQUXgIhyuK4k1g+pld1ax1r3I/8keMHppWQvfH4qZCjgcwG4635VS1CNSQSsKsoVL0Rz1a0GJDVpLaYcvQ0CRgiRfr1A7wsWVeHyivY7Lekw/aSkSkdcPMJC9tzjZ2axBZ6rZPDtlqoqtYatOVHiZEVq8npXaJimBXUf4A+SlusOdPMOi6G4CLtrUs3alufjn5NxJyeNwq8SAOMVrNFKUC4c1nDDEixmw9Fh9hPESbYZudI672917aoE2w50EjBAedEuPPS5cFiaXU8FzdZji4=
  file: release.tar.gz
  on:
    repo: sanger/quanthub
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^devel|master$ # only build a release on devel and master branches

